server:
  env_name: ${APP_ENV:prod}
  port: ${PORT:8001}

data:
  local_data_folder: local_data/private_gpt

ui:
  enabled: true
  
  path: /

llm:
  mode: mock

local:
  llm_hf_repo_id: TheBloke/Llama-2-13B-chat-GGUF
  llm_hf_model_file: llama-2-13b-chat.Q6_K.gguf
  embedding_hf_model_name: BAAI/bge-small-en-v1.5

sagemaker:
  endpoint_name: huggingface-pytorch-tgi-inference-2023-09-25-19-53-32-140

openai:
  api_key: ${OPENAI_API_KEY:}
